# Generated by Django 4.2.5 on 2023-09-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
