# Generated by Django 4.2.5 on 2023-09-26 14:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-slug-value', editable=False, populate_from='title'),
        ),
    ]
