# Generated by Django 4.2.5 on 2023-09-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='NewComment',
        ),
    ]
