# Generated by Django 4.2.5 on 2023-09-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_comment_newcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewComment',
            new_name='Comment',
        ),
    ]
