# Generated by Django 4.2.5 on 2023-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_comment_votes_remove_question_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='question',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
