# Generated by Django 4.2.5 on 2023-09-28 13:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_question_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contents',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
