# Generated by Django 4.2.5 on 2023-09-28 13:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_question_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contents',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
